### ISSUE TITLE
First run error

### ISSUE THREAD

**Issue by shawinder** [lifebeyondfife/npm-rescue#20]
Hi,

I installed the rescue package and defined the Source and destination directories. But it gave me following error after that:

```
Created config file in C:\Users\xxx\.npm-rescue\npm-rescue-config.json...
Backing up xxx...

Git#then is deprecated after version 1.72 and will be removed in version 2.x
Please switch to using Git#exec to run arbitrary functions as part of the command chain.

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by lifebeyondfife** [comment]
Hello Shawinder,

Thank you for the interest and feedback for the npm-rescue library. As noted in the README.md, the problem that this library aimed to solve was the issue of "Leftpad-like events" where developers could remove libraries from npm and updating would leave unresolved dependencies. This specific problem can be solved more easily by using the yarn package manager, which caches downloads: https://yarnpkg.com/lang/en/

As such, the npm-rescue project will not be updated or supported.

Cheers,
Iain
